### ISSUE TITLE
Why a different program?

### ISSUE THREAD

**Issue by explosion-mental** [SpencerApel/sxvv#5]
Can this be an added functionality on sxiv? I would probably use your program but, why don't merge it with like a flag or options on sxiv?

Also idk if you still working on this or if there's something on sxiv already or even maybe this is personal use, if so sorry for the issue.

**Comment by SpencerApel** [comment]
Well, Im not the developer of sxiv, and that project only focuses on pictures. I would love for the functionality to be in sxiv. But I figured I knew enough C and could strip out the features of sxiv and allow for videos.
